site_name: Unsat
site_url: https://github.com/UNSAT3D/unsat
repo_url: https://github.com/UNSAT3D/unsat
repo_name: Unsat

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - H5 data preparation: data.md
  - Examples:
    - Configuration: config.md
    - Visualization: notebooks/visualization.ipynb
  - U-net 2d vs 3d: 2dvs3d.md
  - Python API:
    - unsat: api/api.md
    - train: api/train.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - 🔗 Source code: https://github.com/UNSAT3D/unsat
  - 🔗 Issues: https://github.com/UNSAT3D/unsat/issues

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - attr_list
  - markdown_include.include:
      base_path: docs
  - pymdownx.extra
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
- search
- mkdocstrings:
    # https://mkdocstrings.github.io/usage/
    handlers:
      python:
        paths: [src]
        import:
        - https://docs.python.org/3/objects.inv
        - https://numpy.org/doc/stable/objects.inv
        - https://matplotlib.org/stable/objects.inv
        - https://pymatgen.org/objects.inv
        options:
          docstring_style: numpy
          docstring_options:
            ignore_init_summary: yes
          show_submodules: no
          show_source: true
          show_root_heading: false
          show_root_full_path: false
          docstring_section_style: list
          members_order: alphabetical
          merge_init_into_class: yes
          filters: ["!^_"]
- mkdocs-jupyter:
    include_source: True
    include_requirejs: true  # Fix plotly rendering: https://github.com/danielfrg/mkdocs-jupyter/issues/107

watch:
  - unsat/
  - docs/
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
